### ISSUE TITLE
Installing the extension

### ISSUE THREAD

**Issue by gsueur** [espona/ckanext-restricted#1]
Hi,
I'm trying to install your interesting plugin into my CKAN 2.6a installation, and all I get is : 
`(default)debian@ckan:/usr/lib/ckan/default/src$ pip install ckanext-restricted
Downloading/unpacking ckanext-restricted
  Could not find any downloads that satisfy the requirement ckanext-restricted
Cleaning up...
No distributions at all found for ckanext-restricted
Storing debug log for failure in /home/debian/.pip/pip.log`

**Comment by espona** [comment]
Dear Guillaume

You are the first person interested in this extension. I have just
registered it to PyPI (https://pypi.python.org/pypi/ckanext-restricted/0.0.1).
Could you please try again?
If it doesn't work, I will look for an alternative solution.

Thanks a lot for you interest, please report any bug you may find.

Best,
Lucia

**Comment by gsueur** [comment]
HI Lucia,
Glad to hear from you in such a short time ! I'm gonna give it a try and let you know. We are really interested in it as it supports a missing key feature for us ! 
Best regards

**Comment by gsueur** [comment]
Hi again. 

The pip install went apparently well and the extension seems correctly installed : 
`(default)root@ckan:/usr/lib/ckan/default/src/ckan/ckanext# ls /usr/lib/ckan/default/lib/python2.7/site-packages/ckanext
geoview  __init__.py  __init__.pyc  restricted	scheming  showcase`

I add 'restricted' to the plugin list in the production.ini the file and restart apache... Nothing new appears in the add resource forms. Do I have to set up something more ? 
Thanks

**Comment by espona** [comment]
Dear Guillaume

This extension requires some fields to be defined in you metadata schema
for the resources.
We use ckanext-scheming and ckanext-composite to define the extra fields
"level" and "allowed_users" (see the Requirements section at
https://github.com/espona/ckanext-restricted/blob/master/README.rst).
If this is a problem for you, we will have to look for an alternative way
of adding this fields to the resource creation form.

Best,
Lucia

**Comment by gsueur** [comment]
Ah ah, can't install ckanext-composite from Pip ! same reason than before, you didnt set up the Pypi repo yet :-)

**Comment by espona** [comment]
Sorry, I just did it now. Are you using scheming already?

Best,
Lucia

**Comment by gsueur** [comment]
yes I do, and I've just installed composite too, added the presets.json to mine, and it's all fine !! 
We are going to investigate a bit on this extension in the comings weeks. If anything wrong shows up, would be available for paid enhancements ? 
Best regards

**Comment by espona** [comment]
Great news.
Let me know which enhancements you need, if Iconsider them important for
the extension itself or useful for us I will be happy to do them for free.
Otherwise we can discuss about it depending how much effort it is.
Please be aware that I am developing for CKAN only since a year and that
the extension hasn't been intensively tested.

Best,
Lucia

**Comment by gsueur** [comment]
I have set up a public DATASET with a PRIVATE resource (authenticated users only) and it shows error 500 (apache log says NotAuthorized: Resource access restricted to registered users) on the DATASET display page. is that normal ?

**Comment by espona** [comment]
No, it is not :(
Here it is such a dataset:
http://www.envidat.ch/dataset/ckanext-restricted-test
Here it is the schema we use:
https://github.com/EnviDat/ckanext-envidat_schema/blob/master/ckanext/envidat_schema/datacite_dataset.json#L470

Are you testing this on a public instance I can access?

Sorry
Lucia

**Comment by gsueur** [comment]
It's only a dev environmnent yet. Can I contact you by direct email ? Thx.

**Comment by espona** [comment]
Sure, no problem, my gmail user is lucia.espona.

This is the order of the plugins in my ini file in case it helps:

ckan.plugins = package_converter
               restricted
               stats text_view image_view
               spatial_metadata spatial_query
               envidat_theme envidat_schema
               hierarchy_display
               scheming_datasets scheming_organizations repeating composite
               oaipmh_repository

Best,
Lucia

**Comment by gsueur** [comment]
Wonderfully fixed by your recent improvements. Thanks !

**Comment by espona** [comment]
Thanks to you for helping with troubleshooting :)
