### ISSUE TITLE
Simplify installation

### ISSUE THREAD

**Issue by olivierdalang** [espona/ckanext-restricted#15]
I'm having trouble getting the plugin to work, mainly because of the required extensions that don't want to load despite trying to follow installation instructions (`ckanext.scheming.errors.SchemingException: Could not load ckanext.repeating:presets.json
`, `ImportError: No module named repeating.plugins`, etc.). After a while of fiddling, I think I got dependencies installed, but now ckanext-scheming seems to simply override (instead of extending) my schema, meaning I'd have to redefine all core fields and other plugin fields...

The readme mentions that ckanext-scheming (and others) are recommended, but hints that there's another way.

> Recommends the following extensions (otherwise the configuration is more complicated): * ckanext-scheming * ckanext-repeating * ckanext-composite

What is that more complicated way ?

Does it require modifying the schema using the `update_config_schema()` in a custom extension ? If so, wouldn't it be an option to do this in ckanext-restricted directly, instead of using ckanext-scheming and other dependencies ? Is there an example of such an implementation somewhere ?

It would be really nice if it was a bit easier to install this plugin by removing these dependencies.

**Comment by espona** [comment]
We already use scheming for other reasons and it is widely used extension. The alternative is to add the fields yourself without using scheming which I know it can be done but I never tried.  I will anyway add a link to your repository in case your work helps other people who do not want to use scheming extension, thanks.

**Comment by olivierdalang** [comment]
I'd say it would still make sense to have this commit merged, so that the plugin just works out of the box. It doesn't hinder using ckanext-scheming, does it ? (btw: am I right understanding ckanext-scheming doens't allow to extend the schema, just to completely override it ?)

Note my commit would need some changes to be merged as I removed the nested field stuff to avoid another dependency to ckanext-composite, so it's not backwards compatible.

**Comment by espona** [comment]
I agree but I do not have time right now to work on this, sorry! I will put it on my todo list for whenever I get a chance. Thanks a lot for your contribution.

Yes, scheming completely overrides the schema but in that extension repo you have an json example with the default fields included https://github.com/ckan/ckanext-scheming/blob/master/ckanext/scheming/ckan_dataset.json. So you can just use that and add the necessary fields.

**Comment by olivierdalang** [comment]
> I agree but I do not have time right now to work on this, sorry! I will put it on my todo list for whenever I get a chance. Thanks a lot for your contribution.

I'd suggest to keep the issue open then. An open issue doesn't mean you're willing to work on it for free (too bad for me ;-) ), but that the issue is acknowledged. Then we can agree on what is needed in terms of implementation in this discussion so that it fits most users needs (e.g. make sure it continues to work for ckanext-scheming users). Then whoever has the time can work on this and open a PR.
You can use labels (e.g. "help wanted"), milestones (e.g. "someday") or just assign yourself to issues you're actually working on if you'd like to make it clear you're not planning to work on it.

If you close the issue, is basically means "no, we don't want that in ckanext-restricted", which will lead in me just working on my own fork, without bothering trying to upstream my work, so that we miss a great opportunity of collaboration... Unfortunately it seems in the ckan ecosystem, this is the case for most of extensions, so that they all end up being very out of date and a pain to use/install.

**Comment by espona** [comment]
We developed this extension for our own needs and we are glad to share the code with the community. We provide some minimal support for users who are willing to use as it is and we do not have the resources to now start making tests in all the instances we have for the improvement you suggest, changes have to be justified. It does not bring anything to us and in addition it makes it more complicated to help other developers if now some instances will be using it without scheming extension. Scheming is very popular and widely used, I do not see why is it a big deal to use it. Please feel free to create your own version or directly your own extension using our code and provide such a support to the community if you have the resources for it. Sorry I cannot be of more help, thanks anyway for your interest in the extension.
