### ISSUE TITLE
Estimate to update with CKAN 2.9 ?

### ISSUE THREAD

**Issue by jerbou** [espona/ckanext-restricted#24]
Hi,

We are a "final customer" of a CKAN version which embeds this package in a project that we use.

Is ti possible to update ckanext-restricted to make it works with CKAN 2.9 ?
We could finance the update.

Best Regards,

Jérôme Boutet
IDéO BFC
https://ideo.ternum-bfc.fr/

**Comment by espona** [comment]
Hi Jérôme,

The optimized branch is compatible with CKAN 2.9. Some features have been reduced to make the extension faster, in particular the resources that are linked (containing an URL) are not restricted by the extension, only the uploaded ones.

I hope it works for you: https://github.com/EnviDat/ckanext-restricted/tree/optimized 

Let me know how it went.

Best,
Lucia
