### ISSUE TITLE
CKAN 2.7

### ISSUE THREAD

**Issue by m431m** [espona/ckanext-restricted#3]
Hi,

Is ckan-restricted compatible with CKAN 2.7 release? 

m431m

**Comment by espona** [comment]
Sorry, it is not compatible at the moment.

**Comment by m431m** [comment]
Does it requires a lot of work?

**Comment by espona** [comment]
Since I have no experience with CKAN 2.7 it is hard to say. I will eventually make it compatible but I can't tell when I will have time.

**Comment by m431m** [comment]
I take a look.

**Comment by m431m** [comment]
Ok, I did,  there's not much to be changed. I prepare you the pull-request

**Comment by espona** [comment]
Oh, really? That's great. Will it still work with previous versions? Should I do a branch for CKAN 2.7? Sorry, I am not that experienced with GitHub, I do not know how to handle this. Many thanks!!

**Comment by m431m** [comment]
Yes I guess it still work with previous versions. It is small changes, some bug corrections and improvement (unicode errors and import errors) on the master version.
I check that all is in good on our instance and I open the pull-request with the proposed changes.
