### ISSUE TITLE
2.8

### ISSUE THREAD

**Issue by desaija-lilly** [espona/ckanext-restricted#9]
This extension appears to not be working on CKAN 2.8.

**Comment by espona** [comment]
Could you elaborate on this? It does work in multiple CKAN 2.8 instances. Please make sure you followed the installation and configuration instructions, including the dependencies.

**Comment by espona** [comment]
Could you elaborate on this? It does work in multiple 2.8 CKAN instances. Please make sure you followed carefully the installation and configuration instructions, including the dependences.

**Comment by desaija-lilly** [comment]
Perhaps I'm missing a dependency, but I followed the directions on the GitHub ReadMe.MD - and there were no explicitly required things stated. There was a mention about ckan-scheming, but I would suggest a dependencies/prereqs section in the GitHub.

**Comment by espona** [comment]
It needs ckanext-scheming and ckanext-composite, it’s written on the README.rst in the “Requirements” section, I will try to make it more visible and delete the .md file. One also needs to define some specific fields at resource level, it’s explained there too.

**Comment by desaija-lilly** [comment]
Sorry, I meant I read the rst. I recommend just explicitly saying "you require these extensions first" at the top of the requirements section, the existing language makes it seem a little ambiguous.  Thank you for your quick responses!
